# Generated by Django 4.1.7 on 2023-03-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
