# Generated by Django 4.1.7 on 2023-03-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_courses_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='user',
        ),
    ]
