# Generated by Django 4.1.7 on 2023-03-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_courses_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='coursethumbnail/'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='videofile',
            field=models.FileField(upload_to='coursevideos/'),
        ),
    ]
