# Generated by Django 4.1.7 on 2023-03-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_category_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
    ]
