# Generated by Django 4.1.7 on 2023-03-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_quiz_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('maths', 'maths'), ('science', 'science')], default='general', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('maths', 'maths'), ('science', 'science')], default='general', max_length=10),
        ),
    ]
