# Generated by Django 4.1.7 on 2023-03-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_quiz_category_alter_category_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
