# Generated by Django 4.1.7 on 2023-03-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(default='general', max_length=10),
        ),
    ]
