# Generated by Django 4.1.7 on 2023-03-11 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_studymaterials_alter_quiz_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudyMaterials',
            new_name='StudyMaterial',
        ),
    ]
