# Generated by Django 4.1.7 on 2023-03-11 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_studymaterials_studymaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymaterial',
            old_name='upload',
            new_name='file',
        ),
    ]
